"""Dutch display names for FIFA team keys (CSV / API identifiers stay in English)."""

TEAM_NAMES_NL: dict[str, str] = {
    "Algeria": "Algerije",
    "Argentina": "Argentinië",
    "Australia": "Australië",
    "Austria": "Oostenrijk",
    "Belgium": "België",
    "Bosnia and Herzegovina": "Bosnië-Herzegovina",
    "Brazil": "Brazilië",
    "Canada": "Canada",
    "Cabo Verde": "Kaapverdië",
    "Colombia": "Colombia",
    "Congo DR": "Congo",
    "Croatia": "Kroatië",
    "Curaçao": "Curaçao",
    "Czechia": "Tsjechië",
    "Ecuador": "Ecuador",
    "Egypt": "Egypte",
    "England": "Engeland",
    "France": "Frankrijk",
    "Germany": "Duitsland",
    "Ghana": "Ghana",
    "Haiti": "Haïti",
    "IR Iran": "Iran",
    "Iraq": "Irak",
    "Japan": "Japan",
    "Jordan": "Jordanië",
    "Korea Republic": "Zuid-Korea",
    "Mexico": "Mexico",
    "Morocco": "Marokko",
    "Netherlands": "Nederland",
    "New Zealand": "Nieuw-Zeeland",
    "Norway": "Noorwegen",
    "Panama": "Panama",
    "Paraguay": "Paraguay",
    "Portugal": "Portugal",
    "Qatar": "Qatar",
    "Saudi Arabia": "Saoedi-Arabië",
    "Scotland": "Schotland",
    "Senegal": "Senegal",
    "South Africa": "Zuid-Afrika",
    "Spain": "Spanje",
    "Sweden": "Zweden",
    "Switzerland": "Zwitserland",
    "Tunisia": "Tunesië",
    "Türkiye": "Turkije",
    "Uruguay": "Uruguay",
    "USA": "Verenigde Staten",
    "Uzbekistan": "Oezbekistan",
    "Côte d'Ivoire": "Ivoorkust",
}


def display_team_name(team: str) -> str:
    return TEAM_NAMES_NL.get(team, team)
